In [90]:
import warnings
import datetime

import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
import math

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

from scipy import stats
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

from xgboost import XGBRegressor
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import LinearSVR

from pandas.plotting import lag_plot

import pyarrow
import fastparquet

import statsmodels

### Lectura del dataset

In [224]:
df = pd.read_parquet('../notebooks_tp2/sin_codificar.parquet')
df

,dni_titular_movimiento,fecha_cupon_movimiento,moneda_movimiento,producto_naranja_movimiento,tipo_producto_tarjeta_movimiento,anio_mes_cupon,sexo_descripcion,monto_ajustado,cargo_sector_desc_hist,edad_cliente,antig_cliente,comercio_cat,estado_civil_cat,region
0,0001686b52949b5461ffcbc766687e45031,2020-08-25,0,PL,0,202008,Hombre,5.52,Sector_Empleado_Comercio,61.0,92,0,Otros,REGION PAMPEANA
1,000220fa96ec5af89817894033f8099c547,2020-08-25,0,PL,0,202008,Mujer,15.68,Sector_Sin_Datos,29.0,2,0,Sin_datos,REGION CUYO
2,0002be202de47dfae9cc2304d91161be595,2020-08-25,0,PL,0,202008,Mujer,5.46,Sector_Sin_Datos,28.0,95,0,Soltero,REGION PAMPEANA
3,000e137d0af42e193be1ff670c00d4d1506,2020-08-25,0,PL,0,202008,Hombre,2.50,Sector_Empleado_Comercio,40.0,151,0,Soltero,REGION PAMPEANA
4,0009d010e4faf69552a814a33832b185877,2020-08-25,0,PL,0,202008,Mujer,2.10,Sector_Empleado_Comercio,36.0,87,0,Soltero,REGION PAMPEANA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124309,0001f61dd2845a7e653ebfdaf22dab3b373,2021-05-14,0,PC,3,202105,Mujer,20329.24,Sector_Empleado_Comercio,48.0,98,0,Casado,REGION PATAGONIA
124310,0001f61dd2845a7e653ebfdaf22dab3b373,2021-05-14,0,PC,3,202105,Mujer,20329.24,Sector_Empleado_Comercio,48.0,98,0,Casado,REGION PATAGONIA
124311,0006c15ca823454b68c189da1344d9d7317,2021-05-14,0,PC,3,202105,Hombre,13210.67,Sector_No_Operativo,66.0,105,0,Casado,REGION NORDESTE
124312,0000ab27a0ed815f947df8bcb834ff97975,2021-05-03,0,PC,3,202105,Hombre,121.73,Sector_Empleado_Comercio,74.0,140,0,Soltero,REGION NOROESTE
124313,0000ab27a0ed815f947df8bcb834ff97975,2021-05-03,0,PC,3,202105,Hombre,12284.16,Sector_Empleado_Comercio,74.0,140,0,Soltero,REGION NOROESTE

In [225]:
df.loc[:,'fecha_cupon_movimiento'] = pd.to_datetime(df['fecha_cupon_movimiento']).astype(int)/10**11

In [226]:
df.loc[:, 'moneda_movimiento'] = df['moneda_movimiento'].astype(str)

In [227]:
df.dtypes

dni_titular_movimiento               object
fecha_cupon_movimiento              float64
moneda_movimiento                    object
producto_naranja_movimiento          object
tipo_producto_tarjeta_movimiento     object
anio_mes_cupon                        int64
sexo_descripcion                     object
monto_ajustado                      float64
cargo_sector_desc_hist               object
edad_cliente                        float64
antig_cliente                         int64
comercio_cat                         object
estado_civil_cat                     object
region                               object
dtype: object

In [228]:
ordinal_ft = 'dni_titular_movimiento'
target = 'monto_ajustado'

# Features numericas
num_features = ['anio_mes_cupon', 'edad_cliente', 'antig_cliente', 'fecha_cupon_movimiento']

# Features categoricas de la transaccion
trans_ft = ['producto_naranja_movimiento', 'tipo_producto_tarjeta_movimiento', 'moneda_movimiento', 'comercio_cat']

# Features categoricas del cliente
client_ft = ['sexo_descripcion', 'cargo_sector_desc_hist', 'estado_civil_cat', 'region']

In [312]:
df = df.sort_values(by = ['anio_mes_cupon'], ascending = True)

cat_transformer = OneHotEncoder(handle_unknown='ignore')

encoder = ColumnTransformer(
    transformers=[
        ('dni', 'drop', [ordinal_ft]),
        ('num', 'passthrough', num_features),
        ('trans', cat_transformer, trans_ft),
        ('client', cat_transformer, client_ft),
        ('target', 'passthrough', [target])])
df_enc = encoder.fit_transform(df)
cols = encoder.get_feature_names()

df_enc.shape

(114212, 55)

In [313]:
df_enc = pd.DataFrame.sparse.from_spmatrix(df_enc, columns=[cols]).sparse.to_dense()

In [333]:
# Agregar feature ordinal al principio del dataframe
cols_o = np.hstack([[ordinal_ft],cols])
df_stack = np.hstack([df[[ordinal_ft]],df_enc])
df_encode = pd.DataFrame(df_stack , columns=cols_o)

# Funciones de agregacion para cada columna
aggr = {} 
aggr.update(dict.fromkeys([x for x in cols if 'client' in x], 'max'))
aggr.update(dict.fromkeys([x for x in cols if 'trans' in x], 'sum'))
aggr.update({target:'sum'})

In [334]:
# Agrupamiento por mes
group = ['dni_titular_movimiento', 'anio_mes_cupon']

df_mes = df_encode.groupby(group).agg(aggr).reset_index() # edad y antiguedad

In [ ]:
# Agrupamiento por fecha
group = ['dni_titular_movimiento', 'fecha_cupon_movimiento']

df_fecha = df_encode.groupby(group).agg(aggr).reset_index() # edad y antiguedad

In [352]:
df_encode.values

array([['000821b0a8bdb0450e97298899adc5a3652', 202007.0, 36.0, ..., 0.0,
        0.0, 28.99],
       ['000bebf8a8a59d314b49994ebd84b107414', 202007.0, 58.0, ..., 0.0,
        0.0, 1176.63],
       ['000821b0a8bdb0450e97298899adc5a3652', 202007.0, 36.0, ..., 0.0,
        0.0, 87.91],
       ...,
       ['0001b49c252907291ca16195773ef104079', 202105.0, 49.0, ..., 0.0,
        0.0, 82.64],
       ['0007d3573a085abc49ede83321981a7d760', 202106.0, 50.0, ..., 0.0,
        0.0, -9.0],
       ['0007d3573a085abc49ede83321981a7d760', 202106.0, 50.0, ..., 0.0,
        0.0, -9.0]], dtype=object)

In [340]:
df_mes.describe()

,anio_mes_cupon,edad_cliente,antig_cliente,client__x0_Hombre,client__x0_Mujer,client__x0_Sin Datos,client__x1_Sector_Educativo,client__x1_Sector_Empleado_Comercio,client__x1_Sector_Financiero,client__x1_Sector_No_Operativo,...,trans__x3_1,trans__x3_2,trans__x3_3,trans__x3_4,trans__x3_5,trans__x3_6,trans__x3_7,trans__x3_8,trans__x3_9,monto_ajustado
count,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,...,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000,7443.000000
mean,202052.953245,49.149536,107.739755,0.460836,0.533118,0.006046,0.058444,0.193202,0.011017,0.084106,...,3.602177,0.547226,0.324735,0.022975,1.703345,0.235658,0.046621,0.099019,2.288728,24197.194262
std,46.437423,14.954749,76.457279,0.498497,0.498935,0.077526,0.234597,0.394836,0.104389,0.277565,...,6.045837,1.874314,1.924541,0.336978,3.562076,1.683610,0.628194,0.929670,5.939887,31009.223800
min,202007.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-27864.760000
25%,202010.000000,36.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2029.270000
50%,202012.000000,47.000000,93.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12700.540000
75%,202103.000000,61.000000,156.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,2.000000,35199.635000
max,202106.000000,85.000000,360.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,72.000000,36.000000,34.000000,14.000000,112.000000,81.000000,28.000000,25.000000,126.000000,300740.420000

In [341]:
df_fecha.describe()

,fecha_cupon_movimiento,edad_cliente,antig_cliente,client__x0_Hombre,client__x0_Mujer,client__x0_Sin Datos,client__x1_Sector_Educativo,client__x1_Sector_Empleado_Comercio,client__x1_Sector_Financiero,client__x1_Sector_No_Operativo,...,trans__x3_1,trans__x3_2,trans__x3_3,trans__x3_4,trans__x3_5,trans__x3_6,trans__x3_7,trans__x3_8,trans__x3_9,monto_ajustado
count,3.198100e+04,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,...,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000,31981.000000
mean,1.608104e+07,49.380664,112.753604,0.466527,0.527688,0.005785,0.073606,0.207592,0.016791,0.079766,...,0.838342,0.127357,0.075576,0.005347,0.396423,0.054845,0.010850,0.023045,0.532660,5631.459832
std,6.941602e+04,14.749501,78.827104,0.498886,0.499241,0.075838,0.261133,0.405589,0.128490,0.270935,...,1.886742,0.621691,0.512762,0.115156,1.036756,0.415228,0.176587,0.255766,1.164827,11325.153935
min,1.593734e+07,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-39645.540000
25%,1.602115e+07,37.000000,46.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,566.060000
50%,1.608509e+07,47.000000,98.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1670.840000
75%,1.614211e+07,61.000000,170.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5502.680000
max,1.621901e+07,85.000000,360.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,35.000000,16.000000,14.000000,5.000000,18.000000,16.000000,10.000000,10.000000,14.000000,180632.220000

In [386]:
dff = df_encode.copy()

In [387]:
X = dff.drop([ordinal_ft, target], axis=1)
y = dff[target]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=0, shuffle=False)

num_transformer = MinMaxScaler()
cat_transformer = 'passthrough'

num_features = [g for g in X.columns if 'client' not in g]
cat_features = [g for g in X.columns if 'client' in g]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_features),
        ('cat', cat_transformer, cat_features)])

xgb = XGBRegressor(random_state=0)
model = Pipeline([
  ('preprocessor', preprocessor),
  ('feature_selection', SelectFromModel(LinearSVR(random_state=0))),
  ('regressor', xgb)
])

model.fit(X_train, y_train)

# Predict
y_train_pred = model.predict(X_train)
y_valid_pred = model.predict(X_val)

/Users/lucianomantovani/opt/miniconda3/envs/diplodatos-ayvd/lib/python3.6/site-packages/sklearn/svm/_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [388]:
# evaluate MSE:
train_error = mean_squared_error(y_train, y_train_pred)
val_error = mean_squared_error(y_val, y_valid_pred)
print(f'Train error {train_error.round(3)}, Valid error {val_error.round(3)}')

Train error 12956791.647, Valid error 12446406.983

In [389]:
# evaluate RMSE:
train_error = np.sqrt(mean_squared_error(y_train, y_train_pred))
val_error = np.sqrt(mean_squared_error(y_val, y_valid_pred))
print(f'Train error RMSE {train_error.round(3)}, Valid error RMSE {val_error.round(3)}')

Train error RMSE 3599.554, Valid error RMSE 3527.947

In [390]:
# evaluate MAE:
train_error = mean_absolute_error(y_train, y_train_pred)
val_error = mean_absolute_error(y_val, y_valid_pred)
print(f'Train error MAE {train_error.round(3)}, Valid error MAE {val_error.round(3)}')

Train error MAE 1459.115, Valid error MAE 1485.406

In [196]:
#PIPELINE PARA REGRESION
# 1.codificar los features categoricos
# 2.Agrupar por fecha y sumar los features de la transaccion
# 3.Separar en train y validacion
# 4.Escalar los features numericos y los categoricos codificados de la transaccion

# el punto 2 sacrifica datos, usar si el modelo es pesado

In [153]:
import datetime
 
def week_number_of_month(date_value):
     return (date_value.isocalendar()[1] - date_value.replace(day=1).isocalendar()[1] + 1)

In [155]:
semana = df['fecha_cupon_movimiento'].apply(week_number_of_month)

In [139]:
df.groupby(pd.Grouper(key='fecha_cupon_movimiento',freq='W')).agg(sum)
#weeks = [g for n, g in df.set_index('timestamp').groupby(pd.TimeGrouper('W'))]

,moneda_movimiento,anio_mes_cupon,monto_ajustado,edad_cliente,antig_cliente
fecha_cupon_movimiento,,,,,
2020-07-05,2,1212042,-8993.26,370.0,570
2020-07-12,0,2424084,-6046.60,566.0,1222
2020-07-19,4,2020070,1061.66,452.0,1164
2020-07-26,339,88883104,777796.43,21453.0,47849
2020-08-02,1412,335130070,4219464.84,83478.0,193827
2020-08-09,963,290891520,4829752.95,73038.0,160495
2020-08-16,1213,333717216,3884872.48,81498.0,177631
2020-08-23,989,711876192,2561579.99,179404.0,428166
2020-08-30,1395,985597132,3947880.69,240565.0,522487
2020-09-06,1246,288872724,4092190.26,71855.0,155263
2020-09-13,1008,276954339,4437770.20,69464.0,155287
2020-09-20,1045,310285824,2953299.54,75814.0,173244
2020-09-27,1498,1471433610,4908481.00,360011.0,835233
2020-10-04,1166,342406237,4301546.27,85301.0,195346
2020-10-11,1091,285238120,5070929.04,68964.0,156928
2020-10-18,1196,322205950,3908696.44,78499.0,174770
2020-10-25,1239,1398919252,4771175.20,344115.0,803610
2020-11-01,1291,342609255,4013337.32,84320.0,191958
2020-11-08,1271,321197490,5163647.87,78688.0,187011
2020-11-15,954,313723083,4460908.80,75769.0,166965
2020-11-22,1137,688049466,3854188.36,172458.0,427647
2020-11-29,1719,1062779919,4614435.20,258588.0,571904
2020-12-06,1395,371095771,5144109.43,90704.0,210373
2020-12-13,1286,302411964,4835983.67,74544.0,168009
2020-12-20,1184,314734696,3814335.98,76288.0,166360
2020-12-27,1920,1510244026,5856282.37,369181.0,851649
2021-01-03,1332,314370010,3863442.51,77909.0,176424
2021-01-10,1268,329424630,5832486.53,80309.0,184180
2021-01-17,1068,345996912,4398954.08,83945.0,185608
2021-01-24,1170,752017821,3790501.30,188151.0,456217
2021-01-31,1291,1147529530,4586717.66,277059.0,606124
2021-02-07,1092,323767404,5061109.17,79830.0,184365
2021-02-14,1176,353880602,5479266.46,87690.0,196504
2021-02-21,1042,282336494,2580963.26,69199.0,160236
2021-02-28,1584,1474334132,5413417.27,362137.0,832975
2021-03-07,1286,382176773,5036103.53,95180.0,213835
2021-03-14,1089,300527161,4916874.70,75244.0,169558
2021-03-21,1178,718476165,4291268.51,177587.0,424478
2021-03-28,1707,1104088713,4222354.48,268599.0,603554
2021-04-04,1290,357925426,3688666.19,86617.0,188894
2021-04-11,1121,339938928,5909720.13,83821.0,192201
2021-04-18,1079,312250680,3712133.16,76768.0,184396
2021-04-25,1002,1365414624,4212731.00,332654.0,773258
2021-05-02,6,65886158,987981.88,16144.0,35606
2021-05-09,2,57397820,2663465.96,13634.0,29082
2021-05-16,2,56993610,2283437.61,14367.0,33075
2021-05-23,0,13743140,698024.87,3159.0,7186
2021-05-30,2,3233682,61410.50,656.0,940